### ISSUE TITLE
Change the jenkinsfile to allow multiple jobs using same machine

### ISSUE THREAD

**Issue by DanyC97** [CentOS-PaaS-SIG/paas-sig-ci#64]
do what is [here](https://pagure.io/pagure/blob/master/f/.cico.pipeline#_22)

**Comment by DanyC97** [comment]
well last night i was troubleshooting with bstinson where because i created another job `paas-sig-ci-dev` we were getting `"Failed to connect to the host via ssh: Shared connection to n46.gusty closed"` when the default and new job were kicking at the same time.

And he said _this only expects 1 checked out machine for the PaaS SIG at any time_ then he suggested to make the above change

**Comment by arilivigni** [comment]
We shouldn't have two jobs anyway.  we just need one to run. If you are talking about running builds concurrently that is different.  Are you pointing to the method to allocate or something else?
