### ISSUE TITLE
paas-ci-cd-dev

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/paas-sig-ci#66]
@DanyC97 please don't disable the paas-ci-cd job 

- I don't think this is the right approach to have an identical job for dev.
- In our CI we have a trigger that picks up PRs and then just calls the production job.  

Let's discuss :) thanks again for all the help

**Comment by DanyC97** [comment]
we had the discussion on irc so i think we are good. I've re-enabled the CI job and will look next for other improvements now that the highest priority (i think) is over
