### ISSUE TITLE
Update to  haproxy 1.8.26 in http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/Packages/h/haproxy18-1.8.23-3.el7.x86_64.rpm

### ISSUE THREAD

**Issue by miheer** [CentOS-PaaS-SIG/paas-sig-ci#99]
Description of problem:
Update to haproxy version 1.8.26 for adding the samesite feature using the attr attribue in haproxy 1.8.26

I have written a samesite feature which is a critical requirement for some users of openshift which is Samesite in openshift router wherein we require the attr attribute of haproxy 1.8.26

Samesite feature https://github.com/openshift/origin/pull/25542

The Dockerfile in the router code https://github.com/openshift/origin/pull/24958#issuecomment-717133548

uses centos-openshift-origin.repo 

https://github.com/openshift/origin/pull/24958/commits/5566962f2f0c97bb46ca1867ed1d19a3e46cc938

which will require the following ->
https://github.com/openshift/origin/pull/24958#issuecomment-717133548
~~~
Wait until the SPRM for the enterprise version is published -> https://ftp.redhat.com/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/
Someone should drop a mail at the CentOS PASS SIG group if someone could start to rebuilt the rpm and publish to the mirror.centos.org repository.
~~~

So we need the latest haproxy version of 1.8 which is 1.8.26 so that the router in OCP 3.11 will use that version and the SameSite feature will work smoothly.

Version-Release number of selected component (if applicable):

Repo centos-openshift-origin.repo
Image openshift/origin-cli  
Current old image 1.8.23 at http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/

which needs to be replaced with haproxy 1.8.26

How reproducible:
Always

References -
https://github.com/openshift/origin/pull/24958
https://bugzilla.redhat.com/show_bug.cgi?id=1891777

**Comment by miheer** [comment]
What are the next steps required by Red Hat. Do we first need to have SPRM for the enterprise version published -> https://ftp.redhat.com/redhat/linux/enterprise/7Server/en/RHOSE/SRPMS/  which will be haproxy 1.8.26

**Comment by frobware** [comment]
@miheer to close out https://bugzilla.redhat.com/show_bug.cgi?id=1879445 I'm closing this PR as we now have access to the newer haproxy version: https://github.com/openshift/origin/pull/25542/commits/9c4e00d3dae737583d17c27339eb47b9ae6d6fe8 - HTH

/close

**Comment by miheer** [comment]
We have fixed this issue.
